version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: 'mongo'
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - nodejs

  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    ports:
      - "15672:15672" # Management interface
      - "5672:5672" # rabbitmq service
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - nodejs

  product-service:
    build: ./product-service
    restart: always
    ports:
      - "3001:3001"
    networks:
      - nodejs
    depends_on:
      - 'mongo'
      - 'rabbitmq'
    environment:
      NODE_ENV: production
      AMQP_URL: amqp://guest:guest@rabbitmq:5672

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    networks:
      - nodejs
    depends_on:
      - 'mongo'
      - 'rabbitmq'
    environment:
      NODE_ENV: production
      AMQP_URL: amqp://guest:guest@rabbitmq:5672

volumes:
   mongo-data:
   rabbitmq-data:
   
networks:
  nodejs:
    driver: bridge